spring:
  datasource:
    url: jdbc:h2:D:/D_Masaüstü/Database/SocailMedia/h2db/data/tokayDb
    username: sa
    password: 
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console.enabled: true
    
    
   