spring:
  datasource:
    url: jdbc:h2:D:/D_Masa端st端/Database/SocailMedia/data/db
    username: sa
    password: 
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console.enabled: true
    
    
    
#D:\D_Masa端st端\Github\SocailMedia\h2db